import Head from "next/head";
import { useState, useEffect, useContext } from "react";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "../styles/Home.module.css";
import pb from "../lib/pocketbase";
import { DataContext } from '../ctx/data'
import { Auth, SeverityBadge } from "../components";
const inter = Inter({ subsets: ["latin"] });

export default function Home() {

    const pbData = useContext(DataContext)
    const status = [
        'Backlog',
        'Development',
        'Testing',
        'Completed'
    ]
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="w-screen h-screen flex justify-center items-center">
        {/* <Auth> */}
          <div className="flex">
            <div className=" h-screen w-full max-w-md border-r border-zinc-700">SIDEBAR</div>
            <div class="flex grow flex-col">
<div className="py-8 w-full border-b border-zinc-700"></div>

              {/* {pbData.projects && (
                <>
                  <h3>Projects</h3>
                  <ul className="mb-4">
                    {pbData.projects.map((item, i) => (
                      <>
                        <li key={i}>
                          <p>
                            <b>{item.title}</b>
                          </p>
                          <div
                            className="text-gray-400"
                            dangerouslySetInnerHTML={{
                              __html: item.description,
                            }}
                          />
                        </li>
                      </>
                    ))}
                  </ul>
                </>
              )} */}
              <div className="p-8">
                <h2>Issues</h2>

              </div>
              {pbData.issues && (
                <>
                  <h3>Issues</h3>
                  <ul className="mb-4">
                    {pbData.issues.map((item, i) => (
                      <li key={i}>
                        <p>
                          <b>{item.title}</b> - {item.created} - {item.status}
                        </p>
                        <div
                          className="text-gray-400"
                          dangerouslySetInnerHTML={{ __html: item.description }}
                        />
                        <div>
                            <SeverityBadge severity={item.severity} />
                        </div>
                      </li>
                    ))}
                  </ul>
                </>
              )}
              {pbData.comments && (
                <>
                  <h3>Comments</h3>
                  <ul className="mb-4">
                    {pbData.comments.map((item, i) => (
                      <li key={i}>
                        <p>
                          <b>{item.text}</b> - {item.created} on <b>{item.expand.issue.title}</b>
                        </p>
                        <div
                          className="text-gray-400"
                          dangerouslySetInnerHTML={{ __html: item.description }}
                        />
                      </li>
                    ))}
                  </ul>
                </>
              )}
            </div>
          </div>
        {/* </Auth> */}
      </div>
    </>
  );
}
